# Write your MySQL query statement below
WITH CTE AS(
    SELECT *,LEAD(STUDENT) OVER(ORDER BY ID) AS NXT,
    LAG(STUDENT) OVER(ORDER BY ID) AS PRV
    FROM SEAT
)

SELECT id , 
CASE 
    WHEN ID%2=0 THEN PRV
    WHEN NXT IS NULL THEN STUDENT
    ELSE NXT
END AS student
FROM CTE

